### ISSUE TITLE
commit

### ISSUE THREAD

**Issue by chenxuuu** [chenxuuu/chouxianghua#1]

**Comment by chenxuuu** [comment]
这里是评论区，请用登陆GitHub账号留言~

**Comment by chenxuuu** [comment]
🤡‍🐘🌸‍🆓🆗‍速☠‍超🚀

**Comment by 520xcy** [comment]
🔥💰6⃣💗

**Comment by LucunJi** [comment]
太🔫了，🤝4⃣了

**Comment by gitelia** [comment]
🤝奶子很‍🤜😫🤛

**Comment by Macyrate** [comment]
🤝叼👇🐎💦，🐵🔥

**Comment by nanarino** [comment]
针德牛啤，不愧是你。

**Comment by hang333** [comment]
‍🆓🆗‍💩🎈‍㊗1⃣💋💋儒‍🦆。 te‍😆gr🅰m💪@ch🅾‍🎊🅰ng🅱ot👴可1⃣‍🆓🆗‍🤡‍🐘🌸

**Comment by whc2001** [comment]
绝了，提👣🌞🈯👴用🤡‍🐘🌸

**Comment by chenxuuu** [comment]
@whc2001 因‍🥀‍🌤🐑更符合💨🈹🐎~

**Comment by Wang-ZhengYi** [comment]
🈶点1⃣4⃣

**Comment by fengbujue2022** [comment]
可以加入一个 抽象话 转 普通话 的功能

**Comment by papadave66** [comment]
👴😂🌶

**Comment by SamuelRK** [comment]
妳钔年qIйɡ人憱叆琓噺鮮の，誰還記得zāйɡ叆家族

**Comment by whc2001** [comment]
@Feng-Bu-Jue 这个比较麻烦，毕竟一个emoji可以对应多个汉字，感觉最多转换回拼音否则词库就太大了

**Comment by chenxuuu** [comment]
@Feng-Bu-Jue @whc2001 转成拼音这个功能可以考虑，晚上开搞

**Comment by YeGuanWei** [comment]
你们年轻人，很危险啊

**Comment by aotemandexiaokucha** [comment]
多谢🤡‍🐘🌸，🤝‍📥推特8⃣废🎈‍💦🐎☠‍喷没了。🐔㊗🤝，🤝💩孙😂川2077

**Comment by spirit1431007** [comment]
👇们年🎈‍👤‍🅰，👃竟还too young，🧣‍🍩🈸么👣闷‍🆓发‍🤜😫🤛👎

**Comment by 0xbba** [comment]
🐭💩🐮🍺，科🐔改变‍🆓🔥

**Comment by chenxuuu** [comment]
@Feng-Bu-Jue @whc2001 转成拼音这个功能已经加上了，但是js分割emoji结果不是很好，导致这个功能不太好用

**Comment by Enaium** [comment]
🎈‍🐭入💊转换💦🍊

**Comment by Sarin071** [comment]
🐶💪‍🥘‍➕生4⃣1⃣，7⃣因🔥福👃‍🎼🈯

**Comment by ParseeX** [comment]
🤝们遇🗾🈸么困♂，👴🧣💊爪巴！😊着面✅‍他！😂除🈳惧💦👄🐵🍝法9⃣💩面✅‍🈳惧！坚持👎💩胜💪！‍➕🈶！🐱💪给！

**Comment by oniyakun** [comment]
搞个api！冲冲冲

**Comment by MHY-mh** [comment]
📌💦🐮🍺,👴💚了

**Comment by Kushim-Jiang** [comment]
锤子不能转换成🔨还玩个🔨

**Comment by desertstsung** [comment]
♂🗾‍🌤9⃣💩👇分✊💦💳口，如‍🥘让👇🀄💚‍🍼‍🥘，👇‍🌠🧣‍🌠❤🤝，❤🎈‍让👤‍拥🈶🚀‍😆，👴‍🌠⛑‍🍼‍🌤👻，曾经和👇1⃣7⃣走‍🥘传说🀄💦❤河，1⃣经被🤝泪💦👁没，变🆗‍痛😭💦❤河

**Comment by tgwl** [comment]
扶门切4⃣君🈯㊗，登🗻望断天‍🦆路。

**Comment by dawn-lc** [comment]
🌶👇💩💉💦🐮🍺

**Comment by JohnRowton** [comment]
🐍🐍‍🐻💦，1⃣经谢了

**Comment by huamiaolee** [comment]
🈶1⃣🐎

**Comment by Adam-Miao** [comment]
🐮🍺！💉🐮🍺

**Comment by JackieGmanLu** [comment]
👇🐎4⃣了

**Comment by Ry2an** [comment]
🐭💩🐮🍺，建1⃣‍📥⬅1⃣🈹🤡🐘🌸⛑🐎编1⃣7⃣🐱
oo-┈→屬實牛批，建議再莋ㄚΙ個抽象話廗碼編譯噐嗷。等領dаο看我啲慲幈емοjι廗碼贰叁叁叁℡~

**Comment by Erea1** [comment]
🌶💩💉💦🐮🍺

**Comment by Anonymous235** [comment]
儒‍🦆随和，👇🐎4⃣了

**Comment by JamesNong** [comment]
‍🌤💉™绝🏠🈹🐔8⃣️🅰🏠

**Comment by Weidows** [comment]
🐍🐍，1⃣经谢了

**Comment by ccoQQQ** [comment]
💉🐔2⃣🐮👃

**Comment by pityyyyyyyy** [comment]
🏆‍天跟🐔美出‍🎼逛💳🌶，🗻点🈸➰‍甜品778💹‍便‍🐆💨‍🎊入🐵喝🗾剁jiojio💦‍➕芋圆‍➕🧣丁‍➕👴‍🥘‍➕芋👇‍➕🐱🐱碎‍➕脆啵啵‍➕奶盖‍➕🌸生‍➕👁💸‍‍➕红豆‍➕🍺霜💦奶☕👄🐒缓缓口服1⃣🃏‍v⬆🐶入💦3⃣🈚🈳🍬🃏‍，还点了☕百🗾💦分☄⬅了🈹隐藏甜品吃，☕百🗾yyds，😂🐶🐶‍🐆💨‍🎊入隐藏甜品🐒🐵吃🗾翘jiojio，💉💦绝绝子 ～还点了☕百🗾💦分☄⬅了🈹隐藏甜品吃 💉💦绝绝子🅰！！☕百🗾💦分☄9⃣💩yyds ❤‍🦆路⬆遇🗾1⃣🈹普💚♂，⬇🧑⬇🧑💉⬇🧑， 🏆‍天跟🐔美👴💩‍📥‍🍑🈺㊗💦1⃣天 ‍🚢，💗天🈶🉐‍🌠学😂🌶🐵烦🅰感觉🤝💦💩🈶们☠🐵🐇‍ 连live house💩🈸么☠🧣🈯🗾👴🧣👋🌶🌞飞🚙‍ 🧣说了，💗天🈶💩干饭👤‍干饭魂💦1⃣天

**Comment by yblui** [comment]
good

**Comment by Michaekso** [comment]
👇‍🌤瓜多少💰1⃣🏆‍

**Comment by chenxuuu** [comment]
@Michaekso 💡🚀💰1⃣🏆‍

**Comment by YUQILove** [comment]
逆天

**Comment by Aaron-Alison** [comment]
生🆗‍💩🎈‍㊗1⃣💋💋儒‍🦆

**Comment by Xuziheng01** [comment]
💉💦🐮👃，🐮👃🐮👃

**Comment by Aaron-Alison** [comment]
This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you.——Honey Potter

**Comment by Aaron-Alison** [comment]
so what do u mean????






------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "chenxuuu/chouxianghua"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Apr 11, 2022 04:43 PM
***@***.***&gt;;
Cc:&nbsp;"Honey ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [chenxuuu/chouxianghua] commit (#1)





 
💉💦🐮👃，🐮👃🐮👃

**Comment by D3M0NPL4YER** [comment]
🤝🈶冰🐔0⃣

**Comment by Aaron-Alison** [comment]
This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you.——Honey Potter

**Comment by D3M0NPL4YER** [comment]
👋🤝说谢谢👇因‍🥀🈶👇💋暖了4⃣🐔谢谢👇感谢🈶👇💩💳更美💪🤝💊谢谢👇因‍🥀🈶👇❤‍📏‍📥💚💦谢谢👇感谢🈶👇

**Comment by Aaron-Alison** [comment]
啊这啊这啊这扔个提问箱链接https://www.tapechat.net/uu/RK0914/FKKFK0EM?uid=2795206
&nbsp;


Honey&nbsp;Potter
***@***.***

霍格沃茨魔法学院斯莱特林学院
斯莱特林级长
斯莱特林地下室公共休息室
OurWizardingWorld工作室


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月22日(星期天) 下午2:48
收件人: ***@***.***&gt;; 
抄送: "Honey ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenxuuu/chouxianghua] commit (#1)





 
👋🤝说谢谢👇因‍🥀🈶👇💋暖了4⃣🐔谢谢👇感谢🈶👇💩💳更美💪🤝💊谢谢👇因‍🥀🈶👇❤‍📏‍📥💚💦谢谢👇感谢🈶👇
 
&mdash;

**Comment by Aaron-Alison** [comment]
浅扔一个提问箱
https://www.tapechat.net/uu/RK0914/FKKFK0EM?uid=2795206


***@***.***
 
From: D3M0NPL4YER
Date: 2022-05-22 14:48
To: chenxuuu/chouxianghua
CC: Honey Potter; Comment
Subject: Re: [chenxuuu/chouxianghua] commit (#1)
说谢谢因‍暖了4⃣谢谢感谢更美谢谢因‍❤‍‍谢谢感谢

**Comment by Aaron-Alison** [comment]
病毒不是最可怕的敌人，污名化才是。“法轮功”炒作“中共病毒”的行为，再次暴露了其“借疫反中”，甘当西方反华势力棋子的险恶用心。这副邀功请赏、摇尾乞怜的姿态，实为全体中华儿女所不齿。胜利的曙光就在眼前！除邪去害，邪教借疫情捣乱破坏必败！




&nbsp;

**Comment by Aaron-Alison** [comment]
病毒不是最可怕的敌人，污名化才是。“法轮功”炒作“中共病毒”的行为，再次暴露了其“借疫反中”，甘当西方反华势力棋子的险恶用心。这副邀功请赏、摇尾乞怜的姿态，实为全体中华儿女所不齿。胜利的曙光就在眼前！除邪去害，邪教借疫情捣乱破坏必败！


&nbsp;


Honey&nbsp;Potter
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月22日(星期天) 下午2:48
收件人: ***@***.***&gt;; 
抄送: "Honey ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenxuuu/chouxianghua] commit (#1)





 
👋🤝说谢谢👇因‍🥀🈶👇💋暖了4⃣🐔谢谢👇感谢🈶👇💩💳更美💪🤝💊谢谢👇因‍🥀🈶👇❤‍📏‍📥💚💦谢谢👇感谢🈶👇
 
&mdash;

**Comment by Aaron-Alison** [comment]
《中华人民共和国刑法》第三百条第一款规定：组织、利用会道门、邪教组织或者利用迷信破坏国家法律、行政法规实施的，处三年以上七年以下有期徒刑，并处罚金；情节特别严重的，处七年以上有期徒刑或者无期徒刑，并处罚金或者没收财产；情节较轻的，处三年以下有期徒刑、拘役、管制或者剥夺政治权利，并处或者单处罚金。

《中华人民共和国治安管理处罚法》第二十七条规定：有下列行为之一的，处十日以上十五日以下拘留，可以并处一千元以下罚款;情节较轻的，处五日以上十日以下拘留，可以并处五百元以下罚款：

(一)组织、教唆、胁迫、诱骗、煽动他人从事邪教、会道门活动或者利用邪教、会道门、迷信活动，扰乱社会秩序、损害他人身体健康的；

(二)冒用宗教、气功名义进行扰乱社会秩序、损害他人身体健康活动的。

&nbsp;


Honey&nbsp;Potter
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月22日(星期天) 下午2:48
收件人: ***@***.***&gt;; 
抄送: "Honey ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenxuuu/chouxianghua] commit (#1)





 
👋🤝说谢谢👇因‍🥀🈶👇💋暖了4⃣🐔谢谢👇感谢🈶👇💩💳更美💪🤝💊谢谢👇因‍🥀🈶👇❤‍📏‍📥💚💦谢谢👇感谢🈶👇
 
&mdash;

**Comment by chenxuuu** [comment]
已屏蔽该用户

**Comment by Zhang-gong** [comment]
❤🐎太⛑派🌶❤🐎太⛑派🌶❤🐎太⛑派🌶❤🐎太⛑派🌶❤🐎太⛑派🌶

**Comment by dimffedgr** [comment]
评论‍🎼🈚👁✋7⃣💦

**Comment by MarvelousXiang** [comment]
能🧣能🐵🐵说🌸？🧣能！

**Comment by real-jiakai** [comment]
坚持防1⃣100年🧣‍🍩💊

**Comment by real-jiakai** [comment]
‍➕👤‍们

**Comment by qgmzmy** [comment]
🤝‍🍼💩💩

**Comment by abcdcq** [comment]
评论‍🎼🐵🤡🐘

**Comment by WarriorBrightstar** [comment]
1⃣群傻👃，没💩翻1⃣🤝干🐎？➰‍🉐没💩干🅰！

**Comment by ChaneyChokin** [comment]
太🤡🐘🌶

**Comment by WarriorBrightstar** [comment]
“💚0⃣🐔🍬”喝多了，9⃣🆗‍了🈶☠💦‍🍩‍🎊。🌶些‍➕‍🤜😫🤛🈳💦🐔血💋字，‍📥👤‍生💦💨雨和👀坷面💰，简🈯🧣🈯1⃣提。

**Comment by bizarrey6** [comment]
非‍📏🐵网👴，💩🤝💨狂敲‍🤜😫🤛键盘
